# Generated by Django 5.2.8 on 2025-11-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('name', models.CharField(max_length=40)),
                ('prof_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('rating', models.FloatField()),
                ('branch', models.CharField(max_length=5)),
                ('gender', models.CharField(max_length=10)),
                ('phone', models.BigIntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=40)),
                ('usn', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cgpa', models.FloatField()),
                ('branch', models.CharField(max_length=5)),
                ('gender', models.CharField(max_length=10)),
                ('phone', models.BigIntegerField(max_length=10)),
            ],
        ),
    ]
